import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE_DIR = join(ROOT, "icons", "outline");
export const METADATA_FILE = join(ROOT, "icons", "metadata.json");
export const CORE_DIR = join(ROOT, "packages", "core");
export const REACT_DIR = join(ROOT, "packages", "react");

export const CATEGORIES = ["core-ui", "code", "browser"] as const;
export type Category = (typeof CATEGORIES)[number];

export interface IconMetadata {
  name: string;
  category: Category;
  tags: string[];
  aliases: string[];
  tier: "free";
  since: string;
}

export type Attrs = Record<string, string>;
export type IconNode = Array<[tag: string, attrs: Attrs]>;

export interface ParsedSvg {
  root: Attrs;
  children: IconNode;
  /** Anything between the children that is not whitespace (text, comments, nested tags). */
  leftover: string;
}

const ATTR_RE = /([\w:-]+)\s*=\s*"([^"]*)"/g;
const CHILD_RE = /<([a-zA-Z][\w-]*)\b([^>]*?)\s*\/>/g;

function parseAttrs(source: string): Attrs {
  const attrs: Attrs = {};
  for (const [, key, value] of source.matchAll(ATTR_RE)) attrs[key] = value;
  return attrs;
}

/**
 * Minimal parser for the flat SVGs this repo allows: one <svg> root whose
 * children are self-closing shape elements. Anything else ends up in
 * `leftover`, which the linter reports.
 */
export function parseSvg(source: string): ParsedSvg {
  const match = source.match(/^\s*<svg\b([^>]*)>([\s\S]*)<\/svg>\s*$/);
  if (!match) throw new Error("Expected a single <svg>…</svg> root element");
  const [, rootAttrs, body] = match;
  const children: IconNode = [];
  for (const [, tag, attrs] of body.matchAll(CHILD_RE)) children.push([tag, parseAttrs(attrs)]);
  return { root: parseAttrs(rootAttrs), children, leftover: body.replace(CHILD_RE, "").trim() };
}

export function readMetadata(): IconMetadata[] {
  return JSON.parse(readFileSync(METADATA_FILE, "utf8"));
}

export function listSvgNames(dir: string): string[] {
  return readdirSync(dir)
    .filter((file) => file.endsWith(".svg"))
    .map((file) => file.slice(0, -4))
    .sort();
}

export function toPascalCase(name: string): string {
  return name.replace(/(^|-)([a-z0-9])/g, (_, __, char: string) => char.toUpperCase());
}

export const GENERATED_HEADER = "// Generated by scripts/%s. Do not edit by hand.\n";
